#!/usr/bin/env python
#-*- coding: utf-8 -*-

import os
import ntpath
import argparse
from pypc.pypc import Package
from pypc import __title__

def argparser():
    """
    options:
        o - offline (does not pip install dependencies)
    """
    parser = argparse.ArgumentParser(description=__title__)
    parser.add_argument(dest="path", help="Package full path")
    parser.add_argument('--author', dest="author", help="Author's name",
                        default='')
    parser.add_argument('--email', dest="email", help="Author's email",
                        default='')
    parser.add_argument('--version', dest="version", help="Package version",
                        default='0.0.1')
    parser.add_argument('--desc', dest="desc", help="Package desc",
                        default='no description available')
    parser.add_argument('--url', dest="url", help="Package url",
                        default='')
    return parser

def normalize_path(path):
    if os.sep in path:
        return path
    return os.path.join(os.getcwd(), path)

if __name__ == "__main__":
    parser = argparser()
    args = parser.parse_args()

    options = {
        'path': normalize_path(args.path),
        'pkgname' : ntpath.split(args.path)[-1],
        'author': args.author,
        'email': args.email,
        'version': args.version,
        'classifiers': [], #todo
        'url': args.url,
        'desc': args.desc,
        'venv': 'venv'
        }
    pkg = Package(**options)
    pkg.new()
    pkg.install_virtualenv()
    pkg.install_requirements()
